INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jan', 'Kowalski', 'Kierownik', NULL, 7000);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystian', 'Kowalczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Sebastian', 'Kwiatkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Kołodziej', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karol', 'Czarnecki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Gabryjel', 'Włodarczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Szewczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Andrzej', 'Wróblewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Grażyna', 'Kowalczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Nowicki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Kaczmarek', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Amanda', 'Marciniak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Szymański', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Ryszard', 'Dudek', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jolanta', 'Zalewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jan', 'Wróbel', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Szymon', 'Majewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jakub', 'Kaźmierczak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Grzegorz', 'Duda', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominika', 'Pietrzak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Paweł', 'Ostrowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adam', 'Borkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Sikorska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Robert', 'Walczak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Marek', 'Pawłowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Janusz', 'Zawadzki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominika', 'Wieczorek', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Janusz', 'Wieczorek', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Zawadzka', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Mateusz', 'Baran', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystian', 'Olszewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystian', 'Sikorski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominik', 'Kozłowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dagmara', 'Michalska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Maciej', 'Górski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Marek', 'Górski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Urbańska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Lukasz', 'Czarnecki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Tomasz', 'Szczepański', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Chmielewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jagoda', 'Konieczny', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Agnieszka', 'Krawczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystian', 'Kowalczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Mateusz', 'Kwiatkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Lukasz', 'Kwiatkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Głowacka', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jan', 'Walczak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Lukasz', 'Zawadzki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Agnieszka', 'Kowalska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Piotrkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Sebastian', 'Baran', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Agnieszka', 'Szczepańska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Rutkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Kamińska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Ostrowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karol', 'Nowicki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystyna', 'Baran', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Maciej', 'Olszewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Sebastian', 'Jabłoński', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Magdalena', 'Rutkowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Grażyna', 'Michalak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Janusz', 'Wiśniewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Zawadzki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Szymon', 'Sawicki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Magdalena', 'Lis', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Krawczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jagoda', 'Sikora', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Sebastian', 'Sokołowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Olszewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Michał', 'Zawadzki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Zalewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Anna', 'Marciniak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jolanta', 'Kowalczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Janusz', 'Olszewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Michał', 'Konieczny', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksander', 'Stępień', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Jankowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Małgorzata', 'Szewczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Anna', 'Kołodziej', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Nowicka', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Maciej', 'Malinowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Tomasz', 'Kalinowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Danuta', 'Michalska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Lukasz', 'Jakubowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Anna', 'Witkowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Lukasz', 'Dąbrowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Kozłowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Maciej', 'Szewczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Gabryjel', 'Kwiatkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Gabryjel', 'Kamiński', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Paweł', 'Sokołowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Maciej', 'Olszewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Andrzej', 'Walczak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Magdalena', 'Wasilewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jakub', 'Grabowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Kalinowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Małgorzata', 'Zalewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Paweł', 'Kowalski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Andrzej', 'Witkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adrianna', 'Mazur', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Anna', 'Majewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adrianna', 'Sobczak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Grażyna', 'Wójcik', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksander', 'Bąk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Marek', 'Kwiatkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Grzegorz', 'Włodarczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Katarzyna', 'Bąk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jolanta', 'Olszewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jan', 'Zalewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksander', 'Stępień', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Janusz', 'Wasilewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Danuta', 'Kołodziej', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Małgorzata', 'Sikora', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominik', 'Borkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Justyna', 'Szczepańska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karol', 'Król', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Paweł', 'Jaworski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Basia', 'Włodarczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Wilk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Marciniak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Kołodziej', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Grażyna', 'Jankowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jagoda', 'Wysocka', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karol', 'Dudek', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Ryszard', 'Rutkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Michał', 'Szczepański', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adam', 'Michalak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krzysztof', 'Sikorski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jolanta', 'Wilk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Małgorzata', 'Baran', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominik', 'Adamczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Danuta', 'Lewandowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dagmara', 'Jabłońska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Janusz', 'Konieczny', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jakub', 'Kamiński', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Magdalena', 'Wysocka', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jolanta', 'Szewczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adam', 'Kubiak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Sebastian', 'Pawlak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Katarzyna', 'Wasilewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominik', 'Wróbel', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dagmara', 'Wiśniewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksander', 'Wojciechowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Katarzyna', 'Jaworska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jakub', 'Dąbrowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Jankowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Jaśińska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Lukasz', 'Kowalski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystyna', 'Jabłońska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dagmara', 'Kowalczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Justyna', 'Woźniak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominik', 'Wysocki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Marek', 'Lis', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Agnieszka', 'Maciejewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Jaśińska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominika', 'Sadowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Justyna', 'Grabowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dominik', 'Nowak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Konieczny', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Basia', 'Sikorska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Sokołowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystian', 'Kaźmierczak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Amanda', 'Duda', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Magdalena', 'Włodarczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Zawadzka', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Krystyna', 'Sadowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Andrzej', 'Szymański', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Andrzej', 'Zawadzki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Ryszard', 'Chmielewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Gabryjel', 'Sokołowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Karolina', 'Król', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Anna', 'Krawczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Gabryjel', 'Czarnecki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Marek', 'Kozłowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Tomasz', 'Pawłowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Dagmara', 'Szczepańska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksander', 'Zieliński', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Piotrkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Kowalczyk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jagoda', 'Pawlak', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Marek', 'Kwiatkowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Agnieszka', 'Rutkowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Danuta', 'Król', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Jakub', 'Lewandowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Stępień', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Maciej', 'Szymański', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Zając', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Wojciech', 'Olszewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Maciejewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Agnieszka', 'Lewandowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Gabryjel', 'Maciejewski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adam', 'Zawadzki', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Tomasz', 'Konieczny', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksandra', 'Tomaszewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Kamil', 'Kozłowski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Bąk', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Joanna', 'Wasilewska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Adam', 'Sikorski', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Piotr', 'Konieczny', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Justyna', 'Kwiatkowska', 'Kierowca', 1, 0);
INSERT INTO  Pracownicy VALUES (DEFAULT, 'Aleksander', 'Sokołowski', 'Kierowca', 1, 0);

INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 7, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 9, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 6, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 3, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 8, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 5, 2);
INSERT INTO Pojazdy VALUES (DEFAULT, 2, 3);
INSERT INTO Pojazdy VALUES (DEFAULT, 4, 1);
INSERT INTO Pojazdy VALUES (DEFAULT, 1, 2);

INSERT INTO Kierowcy VALUES (2, 1, true, false);
INSERT INTO Kierowcy VALUES (3, 2, false, true);
INSERT INTO Kierowcy VALUES (4, 3, true, true);
INSERT INTO Kierowcy VALUES (5, 4, false, true);
INSERT INTO Kierowcy VALUES (6, 5, true, false);
INSERT INTO Kierowcy VALUES (7, 6, true, false);
INSERT INTO Kierowcy VALUES (8, 7, true, true);
INSERT INTO Kierowcy VALUES (9, 8, false, true);
INSERT INTO Kierowcy VALUES (10, 9, true, true);
INSERT INTO Kierowcy VALUES (11, 10, true, false);
INSERT INTO Kierowcy VALUES (12, 11, true, false);
INSERT INTO Kierowcy VALUES (13, 12, false, true);
INSERT INTO Kierowcy VALUES (14, 13, false, true);
INSERT INTO Kierowcy VALUES (15, 14, false, true);
INSERT INTO Kierowcy VALUES (16, 15, false, true);
INSERT INTO Kierowcy VALUES (17, 16, true, true);
INSERT INTO Kierowcy VALUES (18, 17, false, true);
INSERT INTO Kierowcy VALUES (19, 18, false, true);
INSERT INTO Kierowcy VALUES (20, 19, true, false);
INSERT INTO Kierowcy VALUES (21, 20, false, true);
INSERT INTO Kierowcy VALUES (22, 21, true, false);
INSERT INTO Kierowcy VALUES (23, 22, false, true);
INSERT INTO Kierowcy VALUES (24, 23, true, true);
INSERT INTO Kierowcy VALUES (25, 24, true, false);
INSERT INTO Kierowcy VALUES (26, 25, true, false);
INSERT INTO Kierowcy VALUES (27, 26, false, true);
INSERT INTO Kierowcy VALUES (28, 27, true, false);
INSERT INTO Kierowcy VALUES (29, 28, true, false);
INSERT INTO Kierowcy VALUES (30, 29, true, false);
INSERT INTO Kierowcy VALUES (31, 30, true, true);
INSERT INTO Kierowcy VALUES (32, 31, false, true);
INSERT INTO Kierowcy VALUES (33, 32, true, true);
INSERT INTO Kierowcy VALUES (34, 33, true, false);
INSERT INTO Kierowcy VALUES (35, 34, false, true);
INSERT INTO Kierowcy VALUES (36, 35, false, true);
INSERT INTO Kierowcy VALUES (37, 36, true, false);
INSERT INTO Kierowcy VALUES (38, 37, false, true);
INSERT INTO Kierowcy VALUES (39, 38, false, true);
INSERT INTO Kierowcy VALUES (40, 39, true, false);
INSERT INTO Kierowcy VALUES (41, 40, false, true);
INSERT INTO Kierowcy VALUES (42, 41, true, false);
INSERT INTO Kierowcy VALUES (43, 42, false, true);
INSERT INTO Kierowcy VALUES (44, 43, true, false);
INSERT INTO Kierowcy VALUES (45, 44, false, true);
INSERT INTO Kierowcy VALUES (46, 45, false, true);
INSERT INTO Kierowcy VALUES (47, 46, true, false);
INSERT INTO Kierowcy VALUES (48, 47, true, false);
INSERT INTO Kierowcy VALUES (49, 48, true, false);
INSERT INTO Kierowcy VALUES (50, 49, true, false);
INSERT INTO Kierowcy VALUES (51, 50, true, true);
INSERT INTO Kierowcy VALUES (52, 51, false, true);
INSERT INTO Kierowcy VALUES (53, 52, false, true);
INSERT INTO Kierowcy VALUES (54, 53, true, false);
INSERT INTO Kierowcy VALUES (55, 54, true, false);
INSERT INTO Kierowcy VALUES (56, 55, true, true);
INSERT INTO Kierowcy VALUES (57, 56, true, true);
INSERT INTO Kierowcy VALUES (58, 57, false, true);
INSERT INTO Kierowcy VALUES (59, 58, false, true);
INSERT INTO Kierowcy VALUES (60, 59, true, false);
INSERT INTO Kierowcy VALUES (61, 60, true, true);
INSERT INTO Kierowcy VALUES (62, 61, true, false);
INSERT INTO Kierowcy VALUES (63, 62, true, true);
INSERT INTO Kierowcy VALUES (64, 63, true, true);
INSERT INTO Kierowcy VALUES (65, 64, true, false);
INSERT INTO Kierowcy VALUES (66, 65, true, false);
INSERT INTO Kierowcy VALUES (67, 66, true, false);
INSERT INTO Kierowcy VALUES (68, 67, true, true);
INSERT INTO Kierowcy VALUES (69, 68, true, true);
INSERT INTO Kierowcy VALUES (70, 69, true, true);
INSERT INTO Kierowcy VALUES (71, 70, true, false);
INSERT INTO Kierowcy VALUES (72, 71, false, true);
INSERT INTO Kierowcy VALUES (73, 72, false, true);
INSERT INTO Kierowcy VALUES (74, 73, true, true);
INSERT INTO Kierowcy VALUES (75, 74, true, true);
INSERT INTO Kierowcy VALUES (76, 75, true, false);
INSERT INTO Kierowcy VALUES (77, 76, true, true);
INSERT INTO Kierowcy VALUES (78, 77, false, true);
INSERT INTO Kierowcy VALUES (79, 78, true, false);
INSERT INTO Kierowcy VALUES (80, 79, true, false);
INSERT INTO Kierowcy VALUES (81, 80, true, false);
INSERT INTO Kierowcy VALUES (82, 81, true, true);
INSERT INTO Kierowcy VALUES (83, 82, true, true);
INSERT INTO Kierowcy VALUES (84, 83, false, true);
INSERT INTO Kierowcy VALUES (85, 84, true, false);
INSERT INTO Kierowcy VALUES (86, 85, false, true);
INSERT INTO Kierowcy VALUES (87, 86, true, true);
INSERT INTO Kierowcy VALUES (88, 87, false, true);
INSERT INTO Kierowcy VALUES (89, 88, true, false);
INSERT INTO Kierowcy VALUES (90, 89, true, true);
INSERT INTO Kierowcy VALUES (91, 90, true, true);
INSERT INTO Kierowcy VALUES (92, 91, true, false);
INSERT INTO Kierowcy VALUES (93, 92, true, false);
INSERT INTO Kierowcy VALUES (94, 93, true, true);
INSERT INTO Kierowcy VALUES (95, 94, true, false);
INSERT INTO Kierowcy VALUES (96, 95, false, true);
INSERT INTO Kierowcy VALUES (97, 96, true, true);
INSERT INTO Kierowcy VALUES (98, 97, true, false);
INSERT INTO Kierowcy VALUES (99, 98, true, true);
INSERT INTO Kierowcy VALUES (100, 99, true, false);
INSERT INTO Kierowcy VALUES (101, 100, true, false);
INSERT INTO Kierowcy VALUES (102, 101, true, true);
INSERT INTO Kierowcy VALUES (103, 102, false, true);
INSERT INTO Kierowcy VALUES (104, 103, true, false);
INSERT INTO Kierowcy VALUES (105, 104, true, false);
INSERT INTO Kierowcy VALUES (106, 105, true, true);
INSERT INTO Kierowcy VALUES (107, 106, true, false);
INSERT INTO Kierowcy VALUES (108, 107, false, true);
INSERT INTO Kierowcy VALUES (109, 108, true, true);
INSERT INTO Kierowcy VALUES (110, 109, false, true);
INSERT INTO Kierowcy VALUES (111, 110, true, false);
INSERT INTO Kierowcy VALUES (112, 111, false, true);
INSERT INTO Kierowcy VALUES (113, 112, false, true);
INSERT INTO Kierowcy VALUES (114, 113, true, false);
INSERT INTO Kierowcy VALUES (115, 114, true, true);
INSERT INTO Kierowcy VALUES (116, 115, true, true);
INSERT INTO Kierowcy VALUES (117, 116, false, true);
INSERT INTO Kierowcy VALUES (118, 117, true, false);
INSERT INTO Kierowcy VALUES (119, 118, true, false);
INSERT INTO Kierowcy VALUES (120, 119, true, true);
INSERT INTO Kierowcy VALUES (121, 120, true, true);
INSERT INTO Kierowcy VALUES (122, 121, true, false);
INSERT INTO Kierowcy VALUES (123, 122, false, true);
INSERT INTO Kierowcy VALUES (124, 123, false, true);
INSERT INTO Kierowcy VALUES (125, 124, false, true);
INSERT INTO Kierowcy VALUES (126, 125, true, true);
INSERT INTO Kierowcy VALUES (127, 126, true, true);
INSERT INTO Kierowcy VALUES (128, 127, true, true);
INSERT INTO Kierowcy VALUES (129, 128, true, false);
INSERT INTO Kierowcy VALUES (130, 129, true, true);
INSERT INTO Kierowcy VALUES (131, 130, true, true);
INSERT INTO Kierowcy VALUES (132, 131, true, true);
INSERT INTO Kierowcy VALUES (133, 132, false, true);
INSERT INTO Kierowcy VALUES (134, 133, true, false);
INSERT INTO Kierowcy VALUES (135, 134, true, false);
INSERT INTO Kierowcy VALUES (136, 135, true, true);
INSERT INTO Kierowcy VALUES (137, 136, true, true);
INSERT INTO Kierowcy VALUES (138, 137, false, true);
INSERT INTO Kierowcy VALUES (139, 138, true, true);
INSERT INTO Kierowcy VALUES (140, 139, false, true);
INSERT INTO Kierowcy VALUES (141, 140, true, true);
INSERT INTO Kierowcy VALUES (142, 141, true, true);
INSERT INTO Kierowcy VALUES (143, 142, true, false);
INSERT INTO Kierowcy VALUES (144, 143, true, false);
INSERT INTO Kierowcy VALUES (145, 144, true, true);
INSERT INTO Kierowcy VALUES (146, 145, false, true);
INSERT INTO Kierowcy VALUES (147, 146, true, true);
INSERT INTO Kierowcy VALUES (148, 147, true, true);
INSERT INTO Kierowcy VALUES (149, 148, true, true);
INSERT INTO Kierowcy VALUES (150, 149, true, true);
INSERT INTO Kierowcy VALUES (151, 150, false, true);
INSERT INTO Kierowcy VALUES (152, 151, true, true);
INSERT INTO Kierowcy VALUES (153, 152, true, false);
INSERT INTO Kierowcy VALUES (154, 153, true, true);
INSERT INTO Kierowcy VALUES (155, 154, false, true);
INSERT INTO Kierowcy VALUES (156, 155, false, true);
INSERT INTO Kierowcy VALUES (157, 156, false, true);
INSERT INTO Kierowcy VALUES (158, 157, true, true);
INSERT INTO Kierowcy VALUES (159, 158, true, true);
INSERT INTO Kierowcy VALUES (160, 159, false, true);
INSERT INTO Kierowcy VALUES (161, 160, true, false);
INSERT INTO Kierowcy VALUES (162, 161, true, false);
INSERT INTO Kierowcy VALUES (163, 162, false, true);
INSERT INTO Kierowcy VALUES (164, 163, true, true);
INSERT INTO Kierowcy VALUES (165, 164, true, false);
INSERT INTO Kierowcy VALUES (166, 165, true, false);
INSERT INTO Kierowcy VALUES (167, 166, false, true);
INSERT INTO Kierowcy VALUES (168, 167, true, true);
INSERT INTO Kierowcy VALUES (169, 168, true, true);
INSERT INTO Kierowcy VALUES (170, 169, true, false);
INSERT INTO Kierowcy VALUES (171, 170, true, false);
INSERT INTO Kierowcy VALUES (172, 171, true, false);
INSERT INTO Kierowcy VALUES (173, 172, false, true);
INSERT INTO Kierowcy VALUES (174, 173, false, true);
INSERT INTO Kierowcy VALUES (175, 174, false, true);
INSERT INTO Kierowcy VALUES (176, 175, true, true);
INSERT INTO Kierowcy VALUES (177, 176, true, false);
INSERT INTO Kierowcy VALUES (178, 177, true, true);
INSERT INTO Kierowcy VALUES (179, 178, false, true);
INSERT INTO Kierowcy VALUES (180, 179, true, false);
INSERT INTO Kierowcy VALUES (181, 180, true, false);
INSERT INTO Kierowcy VALUES (182, 181, true, true);
INSERT INTO Kierowcy VALUES (183, 182, true, true);
INSERT INTO Kierowcy VALUES (184, 183, false, true);
INSERT INTO Kierowcy VALUES (185, 184, true, true);
INSERT INTO Kierowcy VALUES (186, 185, false, true);
INSERT INTO Kierowcy VALUES (187, 186, false, true);
INSERT INTO Kierowcy VALUES (188, 187, true, false);
INSERT INTO Kierowcy VALUES (189, 188, true, true);
INSERT INTO Kierowcy VALUES (190, 189, true, false);
INSERT INTO Kierowcy VALUES (191, 190, true, true);
INSERT INTO Kierowcy VALUES (192, 191, false, true);
INSERT INTO Kierowcy VALUES (193, 192, false, true);
INSERT INTO Kierowcy VALUES (194, 193, false, true);
INSERT INTO Kierowcy VALUES (195, 194, true, true);
INSERT INTO Kierowcy VALUES (196, 195, true, true);
INSERT INTO Kierowcy VALUES (197, 196, true, false);
INSERT INTO Kierowcy VALUES (198, 197, false, true);
INSERT INTO Kierowcy VALUES (199, 198, true, false);
INSERT INTO Kierowcy VALUES (200, 199, false, true);
INSERT INTO Kierowcy VALUES (201, 200, true, false);

